[package]
name = "knackpunkt"
version = "0.1.0"
authors = ["janfriderici <jan@gutencode.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "0.1.2"
pest = "2.1.3"
pest_derive = "2.1.0"
